"""Initial migration with vote_month columns

Revision ID: 001_initial
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Users table
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('emp_nm', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_emp_no'), 'users', ['emp_no'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    
    # Menu table
    op.create_table('menu',
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menu_menu_id'), 'menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_menu_type'), 'menu', ['menu_type'], unique=False)
    
    # Place table
    op.create_table('place',
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('place_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_place_place_id'), 'place', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_place_name'), 'place', ['place_name'], unique=False)
    
    # UserMenuVote table with vote_month
    op.create_table('user_menu_vote',
    sa.Column('vote_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('vote_month', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_index(op.f('ix_user_menu_vote_menu_id'), 'user_menu_vote', ['menu_id'], unique=False)
    op.create_index(op.f('ix_user_menu_vote_user_id'), 'user_menu_vote', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_menu_vote_vote_id'), 'user_menu_vote', ['vote_id'], unique=False)
    op.create_index(op.f('ix_user_menu_vote_vote_month'), 'user_menu_vote', ['vote_month'], unique=False)
    
    # UserPlaceVote table with vote_month
    op.create_table('user_place_vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('vote_month', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.place_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_place_vote_id'), 'user_place_vote', ['id'], unique=False)
    op.create_index(op.f('ix_user_place_vote_place_id'), 'user_place_vote', ['place_id'], unique=False)
    op.create_index(op.f('ix_user_place_vote_user_id'), 'user_place_vote', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_place_vote_vote_month'), 'user_place_vote', ['vote_month'], unique=False)
    
    # UserDateVote table with vote_month
    op.create_table('user_date_vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('preferred_date', sa.String(length=20), nullable=False),
    sa.Column('vote_month', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_date_vote_emp_no'), 'user_date_vote', ['emp_no'], unique=False)
    op.create_index(op.f('ix_user_date_vote_id'), 'user_date_vote', ['id'], unique=False)
    op.create_index(op.f('ix_user_date_vote_vote_month'), 'user_date_vote', ['vote_month'], unique=False)
    
    # PlaceVote table with vote_month
    op.create_table('place_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_type', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('vote_month', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.place_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_votes_id'), 'place_votes', ['id'], unique=False)
    op.create_index(op.f('ix_place_votes_place_id'), 'place_votes', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_votes_vote_month'), 'place_votes', ['vote_month'], unique=False)
    
    # Restaurant suggestions tables
    op.create_table('restaurant_suggestions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('restaurant_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_suggestions_emp_no'), 'restaurant_suggestions', ['emp_no'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestions_id'), 'restaurant_suggestions', ['id'], unique=False)
    
    op.create_table('restaurant_suggestion_likes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('suggestion_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['restaurant_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_suggestion_likes_id'), 'restaurant_suggestion_likes', ['id'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestion_likes_suggestion_id'), 'restaurant_suggestion_likes', ['suggestion_id'], unique=False)
    
    op.create_table('restaurant_suggestion_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('suggestion_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['restaurant_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_suggestion_comments_id'), 'restaurant_suggestion_comments', ['id'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestion_comments_suggestion_id'), 'restaurant_suggestion_comments', ['suggestion_id'], unique=False)
    
    op.create_table('restaurant_comment_likes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['restaurant_suggestion_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_comment_likes_comment_id'), 'restaurant_comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_restaurant_comment_likes_id'), 'restaurant_comment_likes', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_comment_likes_id'), table_name='restaurant_comment_likes')
    op.drop_index(op.f('ix_restaurant_comment_likes_comment_id'), table_name='restaurant_comment_likes')
    op.drop_table('restaurant_comment_likes')
    op.drop_index(op.f('ix_restaurant_suggestion_comments_suggestion_id'), table_name='restaurant_suggestion_comments')
    op.drop_index(op.f('ix_restaurant_suggestion_comments_id'), table_name='restaurant_suggestion_comments')
    op.drop_table('restaurant_suggestion_comments')
    op.drop_index(op.f('ix_restaurant_suggestion_likes_suggestion_id'), table_name='restaurant_suggestion_likes')
    op.drop_index(op.f('ix_restaurant_suggestion_likes_id'), table_name='restaurant_suggestion_likes')
    op.drop_table('restaurant_suggestion_likes')
    op.drop_index(op.f('ix_restaurant_suggestions_id'), table_name='restaurant_suggestions')
    op.drop_index(op.f('ix_restaurant_suggestions_emp_no'), table_name='restaurant_suggestions')
    op.drop_table('restaurant_suggestions')
    op.drop_index(op.f('ix_place_votes_vote_month'), table_name='place_votes')
    op.drop_index(op.f('ix_place_votes_place_id'), table_name='place_votes')
    op.drop_index(op.f('ix_place_votes_id'), table_name='place_votes')
    op.drop_table('place_votes')
    op.drop_index(op.f('ix_user_date_vote_vote_month'), table_name='user_date_vote')
    op.drop_index(op.f('ix_user_date_vote_id'), table_name='user_date_vote')
    op.drop_index(op.f('ix_user_date_vote_emp_no'), table_name='user_date_vote')
    op.drop_table('user_date_vote')
    op.drop_index(op.f('ix_user_place_vote_vote_month'), table_name='user_place_vote')
    op.drop_index(op.f('ix_user_place_vote_user_id'), table_name='user_place_vote')
    op.drop_index(op.f('ix_user_place_vote_place_id'), table_name='user_place_vote')
    op.drop_index(op.f('ix_user_place_vote_id'), table_name='user_place_vote')
    op.drop_table('user_place_vote')
    op.drop_index(op.f('ix_user_menu_vote_vote_month'), table_name='user_menu_vote')
    op.drop_index(op.f('ix_user_menu_vote_vote_id'), table_name='user_menu_vote')
    op.drop_index(op.f('ix_user_menu_vote_user_id'), table_name='user_menu_vote')
    op.drop_index(op.f('ix_user_menu_vote_menu_id'), table_name='user_menu_vote')
    op.drop_table('user_menu_vote')
    op.drop_index(op.f('ix_place_place_name'), table_name='place')
    op.drop_index(op.f('ix_place_place_id'), table_name='place')
    op.drop_table('place')
    op.drop_index(op.f('ix_menu_menu_type'), table_name='menu')
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_emp_no'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
