"""Add restaurant suggestions tables

Revision ID: b3398fc301b1
Revises: a76686759a06
Create Date: 2025-10-19 11:49:54.353886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3398fc301b1'
down_revision = 'a76686759a06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_suggestions',
    sa.Column('suggestion_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_nm', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('memo', sa.String(length=1000), nullable=True),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_index(op.f('ix_restaurant_suggestions_emp_no'), 'restaurant_suggestions', ['emp_no'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestions_suggestion_id'), 'restaurant_suggestions', ['suggestion_id'], unique=False)
    op.create_table('restaurant_suggestion_likes',
    sa.Column('like_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('suggestion_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['restaurant_suggestions.suggestion_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_index(op.f('ix_restaurant_suggestion_likes_emp_no'), 'restaurant_suggestion_likes', ['emp_no'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestion_likes_like_id'), 'restaurant_suggestion_likes', ['like_id'], unique=False)
    op.create_index(op.f('ix_restaurant_suggestion_likes_suggestion_id'), 'restaurant_suggestion_likes', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_suggestion_likes_suggestion_id'), table_name='restaurant_suggestion_likes')
    op.drop_index(op.f('ix_restaurant_suggestion_likes_like_id'), table_name='restaurant_suggestion_likes')
    op.drop_index(op.f('ix_restaurant_suggestion_likes_emp_no'), table_name='restaurant_suggestion_likes')
    op.drop_table('restaurant_suggestion_likes')
    op.drop_index(op.f('ix_restaurant_suggestions_suggestion_id'), table_name='restaurant_suggestions')
    op.drop_index(op.f('ix_restaurant_suggestions_emp_no'), table_name='restaurant_suggestions')
    op.drop_table('restaurant_suggestions')
    # ### end Alembic commands ###
